<a href="https://colab.research.google.com/github/sandhya111205/principle-of-datascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform a numericalanalysis and data manipulation usingnumpy library

1.Create a numpy array

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


2.Access and Manipulate elements in the array

In [ ]:
arr1[2]

3

In [ ]:
#change the array element
arr1[2]=5
arr1

array([1, 2, 5])

3. Create a 2-Dimensional array and check the shape of the array

In [ ]:
#create 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#check the  shape of the array
print("The shape is 2 rows and 3 colums :",arr2.shape)

The shape is 2 rows and 3 colums : (2, 3)


4.Access element from the 2D array using index positions


In [ ]:
#Accessing element from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


5. Create an an array of type string

In [ ]:
#create array of string
arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


6.Using the arrange() and linspace() function to evenly space value in a specified interval

In [ ]:
#using arrange() function to evenly space value in specified interval
arr=np.arange(0,20,2)
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#using linspace() function evenly space value in specified interval
arr=np.linspace(0,10,20)
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

7.Create an array of random value between 0 to 1 in a given shape


In [ ]:
#create an array of random value between 0 & 1
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)

[0.79638828 0.96183761 0.47262135 0.15020644 0.51511875 0.56013661
 0.64977841 0.73988492 0.1622466  0.59964596]


[[0.20187742 0.00699809 0.95342301 0.10928346]
 [0.64542317 0.20602252 0.15812709 0.81995122]
 [0.1360938  0.70126742 0.67442751 0.26488522]]


8.Create an array of constant values in a given shape

In [ ]:
#create an arrayof constant value in a given shape
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


9.Repeat each element of an array by a specified number of times using repeat() and tile() functions

In [ ]:
# Create an array by repetation
# Repeat each element of an array by a number of times
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [ ]:
#Repeat an array by a specified number of time using tile () function
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


10.Create an identity matrix using eye() and identity() function

In [ ]:
#create an identity matrix using eye() function
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create an identity matrix using identity() function
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


11.Create a 5X5 2D array for random number between 0 & 1

In [ ]:
#.Create a 5X5 2D array for random number between 0 & 1
arr=np.random.rand(5,5)
print(arr)

[[0.64148415 0.28519045 0.90011306 0.99473709 0.96329733]
 [0.59663431 0.18338756 0.36655675 0.7782899  0.75190704]
 [0.12018549 0.26560486 0.00250217 0.55061902 0.40881752]
 [0.7482142  0.04023396 0.61909465 0.32612568 0.90454048]
 [0.8389639  0.54196166 0.13714282 0.34413576 0.27909573]]


12.Sum an array along the column

In [ ]:
#Sum an array along the column
print(np.sum(arr,axis=0))

[2.94548206 1.31637849 2.02540946 2.99390744 3.30765809]


13.Sum an array along the row

In [ ]:
#Sum an array along the row
print(np.sum(arr,axis=1))

[3.78482208 2.67677556 1.34772906 2.63820897 2.14129988]


14.Calculate the mean ,median,standard deviation and variance

In [ ]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5035534219146872
0.541961657375056
0.29756987268322244
0.0885478291287092


15.Sort an array along the row using the sort() function


In [ ]:
arr=np.random.rand(5,5)
print(arr)

[[0.16739369 0.37467499 0.86178815 0.00443167 0.47230767]
 [0.92015516 0.69897336 0.45341758 0.01507804 0.26041864]
 [0.47494704 0.74143539 0.15495944 0.34332636 0.18642177]
 [0.37683721 0.71260233 0.93417909 0.46358875 0.19240087]
 [0.91705161 0.86936522 0.19473412 0.44736611 0.8313092 ]]


In [ ]:
# sort along the row
print(np.sort(arr,axis=1))

[[0.00443167 0.16739369 0.37467499 0.47230767 0.86178815]
 [0.01507804 0.26041864 0.45341758 0.69897336 0.92015516]
 [0.15495944 0.18642177 0.34332636 0.47494704 0.74143539]
 [0.19240087 0.37683721 0.46358875 0.71260233 0.93417909]
 [0.19473412 0.44736611 0.8313092  0.86936522 0.91705161]]


16.Append element to an array using the append () function

In [ ]:
arr=np.array([4,5,6,7])
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr2=np.append(arr,[8,9,10])
arr2

array([ 4,  5,  6,  7,  8,  9, 10])

17.Delete multipe element in an array


In [ ]:
arr2=np.array([4,5,6,7,8,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  8  9 10 11]


[ 4  6  7  9 10 11]


18.Concatinate elements from 2D array

In [ ]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
#combine array item by column
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
#Combine array item by row
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
